# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np
np.__version__

'2.2.3'

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list) # 1-Dimensional Array

array([1, 2, 3])

In [10]:
arr1 = np.array(my_list)
print(f'Length :  {len(arr1)}')
print(f' Shape : {arr1.shape}')

Length :  3
 Shape : (3,)


In [12]:
my_matrix = [[1,2,3],[4,5,6]]    # ,[7,8,9]
print(f' my_matrix :  {my_matrix}')
print(f' my_matrix type:  {type(my_matrix)}')

 my_matrix :  [[1, 2, 3], [4, 5, 6]]
 my_matrix type:  <class 'list'>


In [13]:
np.array(my_matrix)  # 2-Dimensional Array    - converting list to array in np

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr2 = np.array(my_matrix)
arr2.shape

(2, 3)

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [81]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

### zeros and ones

Generate arrays of zeros or ones

In [20]:
np.zeros(3) # 1-D array

array([0., 0., 0.])

In [21]:
np.zeros((5,4))  # 2-Dimensional

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones(3) # 1-Dimensional

array([1., 1., 1.])

In [23]:
np.ones((3,6),dtype=int) # 2-D array

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### linspace
Return evenly spaced numbers over a specified interval.

In [82]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x0000027DFE6280E0>
File:            c:\users\yasaswini guruju\documents\data_analysis_with_python\.venv\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the s

In [24]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [90]:
print(np.linspace(1,20,4))
print(np.linspace(1,20,4,dtype=int))

[ 1.          7.33333333 13.66666667 20.        ]
[ 1  7 13 20]


In [31]:
np.linspace(1,2,9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [32]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [33]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [34]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [35]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [45]:
E0 = np.eye(4)
print(E0)
print(type(E0))           # default dtype is float for eye
print(type(E0[1,1]))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [46]:
np.eye(3,dtype=float) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
E1 = np.eye(4,dtype=int)
print(E1)
print(type(E1))
print(type(E1[1,1]))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1]``.

In [50]:
np.random.rand(3) # 1D

array([0.56884987, 0.3476615 , 0.57451126])

In [56]:
np.random.rand(2,3) # 2D

array([[0.33088534, 0.88413276, 0.73377107],
       [0.17122839, 0.70988467, 0.31396372]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [57]:
np.random.randn(2) # 1D

array([-1.79698491,  1.26225238])

In [58]:
np.random.randn(2,3) #2D

array([[ 0.3751382 , -0.52997897,  0.08810219],
       [-0.79429637, -0.11720055,  1.64591417]])

In [93]:
np.random.randn(3,10) #2D

array([[-1.27505376,  0.18875066, -1.50389723, -0.69603218, -0.7129655 ,
        -1.20046969, -1.01006954,  0.12399769,  0.2390552 ,  1.08472542],
       [-0.31527341, -1.02854354,  1.2877565 ,  1.0511199 , -0.05630399,
         0.19225862, -0.46369273, -0.54203124,  0.12928229, -0.41562613],
       [ 0.42414158, -0.39740923, -0.25257525, -1.62812564, -0.56130707,
         0.63798058,  0.06174773,  1.57371346,  1.46088254, -1.59157819]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [60]:
np.random.randint(1,100)

18

In [61]:
np.random.randint(1,100,10)

array([52, 30, 41, 58, 30, 66,  1, 74, 30, 27], dtype=int32)

In [63]:
np.random.randint(1,100,10)

array([19, 11, 61, 15, 86, 41, 89, 22, 14, 61], dtype=int32)

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [95]:
arr = np.arange(25)
ranarr = np.random.randint(0,25,10)
print(f' arr : {arr}  \n nanarr : {ranarr}')
ranarr

 arr : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]  
 nanarr : [ 5 21 22  2  6 18 11 24  6  3]


array([ 5, 21, 22,  2,  6, 18, 11, 24,  6,  3], dtype=int32)

## Reshape
Returns an array containing the same data with a new shape.

In [68]:
arr # 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
arr.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [62]:
ranarr = np.random.randint(0,25,10)
ranarr

array([ 8, 20, 15, 20, 24, 22,  7,  2, 21, 23], dtype=int32)

In [63]:
ranarr.shape

(10,)

In [64]:
max(ranarr)

np.int32(24)

In [65]:
print(max(ranarr))

24


In [66]:
print(ranarr.max())

24


In [67]:
print(ranarr.argmax())

4


In [68]:
ranarr

array([ 8, 20, 15, 20, 24, 22,  7,  2, 21, 23], dtype=int32)

In [ ]:
print(ranarr.min())

2


In [70]:
print(ranarr.argmin())

7


## Shape

Shape is an attribute that arrays have (not a method):

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
# Vector or 1-Dimensional Array
arr.shape 

(12,)

In [73]:
# Notice the two sets of brackets
arr.reshape(1,12)  # 2-D array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [75]:
arr.reshape(1,12).shape

(1, 12)

In [76]:
arr.reshape(1,12).shape[0]

1

In [77]:
arr.reshape(1,12).shape[1]

12

In [ ]:
arr.reshape(12,1)

In [ ]:
arr.reshape(12,1).shape

### dtype

You can also grab the data type of the object in the array:

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
arr.dtype

dtype('int64')

In [80]:
arr2 = np.random.rand(5)
arr2

array([0.92660012, 0.92205972, 0.58317351, 0.45652003, 0.33475766])

In [81]:
arr2.dtype

dtype('float64')