In [81]:
import numpy as np

In [2]:
np.array([0,1,2,3])

array([0, 1, 2, 3])

In [3]:
a1=np.array([0,1,2,3])

In [4]:
print(a1)

[0 1 2 3]


In [5]:
type(a1)

numpy.ndarray

In [5]:
a1.shape

(4,)

In [6]:
a2= np.array([1,2.3,4,'hi','hello',7.04])

In [7]:
a2

array(['1', '2.3', '4', 'hi', 'hello', '7.04'], dtype='<U32')

In [8]:
print(a2)

['1' '2.3' '4' 'hi' 'hello' '7.04']


In [12]:
a2.shape

(6,)

In [13]:
type(a2)

numpy.ndarray

In [14]:
np.__version__

'2.2.3'

In [15]:
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [16]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]],
               [[100,200,300],[400,500,600],[700,800,900]]])
print(a3)

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]


In [17]:
a2.shape

(2, 3)

In [18]:
a3.shape

(3, 3, 3)

In [19]:
np.zeros(2)

array([0., 0.])

In [20]:
z=np.zeros(9)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
z.shape

(9,)

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((4,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
o=np.ones(4)

In [23]:
o.shape

(4,)

In [29]:
o1=np.ones((3,4))
print(o1)
print(f' Shape of array : {o1.shape}')

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 Shape of array : (3, 4)


In [43]:
o3=np.ones(shape=(3,4),dtype=int)
print(o3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [38]:
O0 = np.ones((3,5),dtype=str)
O0

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [45]:
o4=np.ones(shape=(3,2,4),dtype=int)
print(o4)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [46]:
np.ones(shape=(2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [56]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Array Broadcasting

In [43]:
input_list = [1,2,3,4]

# Expected Output
# output_list = [2,4,6,8]

In [46]:
output_list = []
for i in input_list:
    output_list.append(i*2)
print(output_list)

[2, 4, 6, 8]


In [51]:
# Using List comprehension
output_list = [i*2 for i in input_list]
output_list

[2, 4, 6, 8]

In [53]:
my_array = np.array([1,2,3,4])
print(my_array*2)

[2 4 6 8]


In [61]:
# From input list [1,2,3,4], create ouput list where each item is mutiplied by 2 

list1=[1,2,3,4]
n_array= np.array(list1)
print(f" Array : {n_array}")
new_array=n_array*2
final_list=new_array.tolist()   # converting array to list using .tolist() 
print(f"Final List : {final_list}")

 Array : [1 2 3 4]
Final List : [2, 4, 6, 8]


In [62]:
input_list = [1,2,3,4]
final_list=((np.array(list1)*2).tolist())
print(final_list)

[2, 4, 6, 8]


In [63]:
np.array(final_list) + 10

array([12, 14, 16, 18])

In [64]:
a = np.array([[1,2],[3,4]])
b = np.array([[10,11],[12,13]])
print(f"a: {a}")
print(f"b:{b}")

a: [[1 2]
 [3 4]]
b:[[10 11]
 [12 13]]


In [65]:
a+b

array([[11, 13],
       [15, 17]])

In [66]:
a-b

array([[-9, -9],
       [-9, -9]])

In [67]:
b-a

array([[9, 9],
       [9, 9]])

In [68]:
b*a

array([[10, 22],
       [36, 52]])

In [69]:
b/a

array([[10.  ,  5.5 ],
       [ 4.  ,  3.25]])

In [71]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
a.shape

(3, 4)

In [73]:
a[2,3]

np.int64(12)

In [105]:
a[2][3]

np.int64(12)

In [110]:
a[0,0:3]

array([1, 2, 3])

In [116]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [120]:
a[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [74]:
a1 = a[1:,1:] / 2
print(a1)
print(f"output : {a1.tolist()}")

[[3.  3.5 4. ]
 [5.  5.5 6. ]]
output : [[3.0, 3.5, 4.0], [5.0, 5.5, 6.0]]


In [133]:
np.array([[1,2,3,4],[5,6,7,8]],dtype=str)

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8']], dtype='<U1')

In [134]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [136]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
b = np.arange(1,13)

In [145]:
b.shape

(12,)

In [146]:
b.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [149]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [155]:
print(b)
b.reshape(3,4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [157]:
np.arange(24).reshape((4,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [85]:
N1 = np.arange(36).reshape((6,6))
N1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [92]:
N1[2:,3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [99]:
print(N1[::2])

print(N1[1::3])

print(N1[2::1])

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [24 25 26 27 28 29]]
[[ 6  7  8  9 10 11]
 [24 25 26 27 28 29]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [119]:
print(N1)
print(f'\nN1[2:4:2] : {N1[2:4:2]}')
print(f'N1[2::2] :\n {N1[2::2]}')
print(f'N1[2::2,2] : {N1[2::2,2]}')
print(f'N1[2::2,:2] : {N1[2::2,:2]}')
print(f'N1[2::2,::2] :  {N1[2::2,::2]}')
print(f'N1[::2,::2] : {N1[::2,::2]}')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

N1[2:4:2] : [[12 13 14 15 16 17]]
N1[2::2] :
 [[12 13 14 15 16 17]
 [24 25 26 27 28 29]]
N1[2::2,2] : [14 26]
N1[2::2,:2] : [[12 13]
 [24 25]]
N1[2::2,::2] :  [[12 14 16]
 [24 26 28]]
N1[::2,::2] : [[ 0  2  4]
 [12 14 16]
 [24 26 28]]
