# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [22]:
import numpy as np
arr = np.arange(0,10)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [27]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\Yasaswini Guruju\AppData\Local\Temp\ipykernel_29524\2878212635.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [30]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\Yasaswini Guruju\AppData\Local\Temp\ipykernel_29524\1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [34]:
arr**(1/2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [36]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [38]:
np.max(arr) #same as arr.max()

np.int64(9)

In [39]:
arr.max()

np.int64(9)

In [40]:
np.min(arr)

np.int64(0)

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
len(arr)

10

In [43]:
np.mean(arr)

np.float64(4.5)

In [46]:
np.std(arr)

np.float64(2.8722813232690143)

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.sin(2)  # for understanding

np.float64(0.9092974268256817)

In [49]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [50]:
np.log(arr)

C:\Users\Yasaswini Guruju\AppData\Local\Temp\ipykernel_29524\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [51]:
np.s*?

np.s_
np.save
np.savetxt
np.savez
np.savez_compressed
np.sctypeDict
np.searchsorted
np.select
np.set_printoptions
np.setbufsize
np.setdiff1d
np.seterr
np.seterrcall
np.setxor1d
np.shape
np.shares_memory
np.short
np.show_config
np.show_runtime
np.sign
np.signbit
np.signedinteger
np.sin
np.sinc
np.single
np.sinh
np.size
np.sort
np.sort_complex
np.spacing
np.split
np.sqrt
np.square
np.squeeze
np.stack
np.std
np.str_
np.strings
np.subtract
np.sum
np.swapaxes

# Great Job!

That's all we need to know for now!

In [55]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [56]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])