In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [5]:
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [8]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
e = np.full((2,2),5)
e

array([[5, 5],
       [5, 5]])

In [11]:
f = np.eye(2) 
f

array([[1., 0.],
       [0., 1.]])

In [12]:
np.random.random((2,2))

array([[0.92774948, 0.06875926],
       [0.51526866, 0.75670397]])

In [23]:
print(np.empty((2,2)))
np.empty((3,2))

[[0.92774948 0.06875926]
 [0.51526866 0.75670397]]


array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [24]:
a.shape

(3,)

In [25]:
c.shape

(2, 2, 3)

In [26]:
len(a)

3

In [34]:
a.ndim #ndim() function return the number of dimensions of an array.

1

In [35]:
b.ndim

2

In [36]:
e.size

4

In [37]:
b.dtype

dtype('float64')

In [38]:
b.dtype.name 

'float64'

In [39]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [40]:
b.astype(int) 

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# np.info(np.ndarray.dtype)
np.info(b)

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1a721ddb3d0
byteorder:  little
byteswap:  False
type: float64


In [42]:
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [43]:
np.subtract(a,b) 

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [44]:
b + a 

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [50]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [51]:
a / b 

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [52]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [53]:
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [54]:
np.multiply(a,b) 

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [55]:
np.exp(b) 

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [56]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [59]:
a

array([1, 2, 3])

In [57]:
np.sin(a) 

array([0.84147098, 0.90929743, 0.14112001])

In [58]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [60]:
np.log(a) 

array([0.        , 0.69314718, 1.09861229])

In [61]:
print(e)
print(f)

[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


In [62]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [64]:
a

array([1, 2, 3])

In [65]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [63]:
a == b

array([[False,  True,  True],
       [False, False, False]])

In [67]:
np.array_equal(a, b) 

False

In [66]:
a < 2

array([ True, False, False])

In [68]:
a[a<2]

array([1])

In [69]:
a.sum()

np.int64(6)

In [72]:
b.sum()

np.float64(21.5)

In [83]:
b.sum(axis=1)

array([ 6.5, 15. ])

In [45]:
b.sum(axis=0)

array([5.5, 7. , 9. ])

In [84]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [85]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [46]:
b.cumsum(axis=0)

array([[1.5, 2. , 3. ],
       [5.5, 7. , 9. ]])

In [47]:
b.max()

np.float64(6.0)

In [48]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [52]:
b.max(axis=1)

array([3., 6.])

In [53]:
a.mean()

np.float64(2.0)

In [54]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [63]:
print(np.abs(b))
print(np.ceil(b)) 
print(np.floor(b))
print(np.round(b))

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[2. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[2. 2. 3.]
 [4. 5. 6.]]


In [64]:
np.array_equal(a,b)

False

In [67]:
### ADDING/REMOVING ELEMENTS
np.append(a,5) # Appends values to end of arr

array([1, 2, 3, 5])

In [68]:
np.insert(a,2,5) # Inserts values into arr before index 2

array([1, 2, 5, 3])

In [72]:
np.delete(b,1,axis=0) # Deletes row on index 3 of arr

array([[1.5, 2. , 3. ]])