In [2]:
import numpy as np

In [2]:
np.array([0,1,2,3])

array([0, 1, 2, 3])

In [3]:
a1=np.array([0,1,2,3])

In [4]:
print(a1)

[0 1 2 3]


In [5]:
type(a1)

numpy.ndarray

In [3]:
a2= np.array([1,2.3,4,'hi','hello',7.04])

In [4]:
a2

array(['1', '2.3', '4', 'hi', 'hello', '7.04'], dtype='<U32')

In [5]:
print(a2)

['1' '2.3' '4' 'hi' 'hello' '7.04']


In [6]:
type(a2)

numpy.ndarray

In [7]:
np.__version__

'2.2.3'

In [19]:
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [20]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]],
               [[100,200,300],[400,500,600],[700,800,900]]])
print(a3)

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]


In [22]:
a2.shape

(2, 3)

In [23]:
a3.shape

(3, 3, 3)

In [25]:
np.zeros(2)

array([0., 0.])

In [27]:
z=np.zeros(9)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
z.shape

(9,)

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((4,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
o=np.ones(4)

In [37]:
o.shape

(4,)

In [40]:
o1=np.ones((3,4))
print(o1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
o3=np.ones(shape=(3,4),dtype=int)
print(o3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [45]:
o4=np.ones(shape=(3,2,4),dtype=int)
print(o4)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [46]:
np.ones(shape=(2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [47]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Array Broadcasting

In [51]:
input_list = [1,2,3,4]

# Expected Output
# output_list = [2,4,6,8]

In [52]:
output_list=[]
for i in input_list:
    output_list.append(i*2)
print(output_list)

[2, 4, 6, 8]


In [53]:
# Using List comprehension
output_list = [i*2 for i in input_list]
print(output_list)

[2, 4, 6, 8]


In [54]:
my_array = np.array([1,2,3,4])

In [55]:
print(my_array*2)

[2 4 6 8]


In [71]:
# From input list [1,2,3,4], create ouput list where each item is mutiplied by 2 

list1=[1,2,3,4]
n= np.array(list1)
print(n)
list2=n*2
final_list=list2.tolist()
print(f"Final List : {final_list}")


[1 2 3 4]
Final List : [2, 4, 6, 8]


In [80]:
input_list = [1,2,3,4]
final_list=((np.array(list1)*2).tolist())
print(final_list)

[2, 4, 6, 8]


In [83]:
np.array(final_list) + 10

array([12, 14, 16, 18])

In [84]:
a = np.array([[1,2],[3,4]])
b = np.array([[10,11],[12,13]])
print(f"a: {a}")
print(f"b:{b}")

a: [[1 2]
 [3 4]]
b:[[10 11]
 [12 13]]


In [85]:
a+b

array([[11, 13],
       [15, 17]])

In [86]:
a-b

array([[-9, -9],
       [-9, -9]])

In [87]:
b-a

array([[9, 9],
       [9, 9]])

In [88]:
b*a

array([[10, 22],
       [36, 52]])

In [89]:
b/a

array([[10.  ,  5.5 ],
       [ 4.  ,  3.25]])

In [91]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [94]:
a.shape

(3, 4)

In [96]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
a[2,3]

np.int64(12)

In [105]:
a[2][3]

np.int64(12)

In [110]:
a[0,0:3]

array([1, 2, 3])

In [116]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [120]:
a[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [131]:
a1 = a[1:,1:] / 2
print(a1)
print(f"output : {a1.tolist()}")

[[3.  3.5 4. ]
 [0.5 5.5 6. ]]
output : [[3.0, 3.5, 4.0], [0.5, 5.5, 6.0]]


In [133]:
np.array([[1,2,3,4],[5,6,7,8]],dtype=str)

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8']], dtype='<U1')

In [134]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [136]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
b = np.arange(1,13)

In [145]:
b.shape

(12,)

In [146]:
b.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [149]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])